# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - cargo build
    silent: true
  
  run:
    vars:
      YEAR: '{{.YEAR | default "2025"}}'
      DAY: '{{.DAY}}'
      FULL_FLAG: '{{if .FULL}}--full{{end}}'
    cmds:
      - |
        if [ -n "{{.DAY}}" ]; then
          cargo run -p runner -- {{.YEAR}} --day {{.DAY}} {{.FULL_FLAG}}
        else
          cargo run -p runner -- {{.YEAR}} {{.FULL_FLAG}}
        fi
    silent: true
