[package]
name = "runner"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
aoc2022 = { path = "../years/aoc2022" }
aoc2023 = { path = "../years/aoc2023" }
aoc2024 = { path = "../years/aoc2024" }
aoc2025 = { path = "../years/aoc2025" }
anyhow = "1"
structopt = "0.3"
inventory = "0.3"
log = "0.4"
env_logger = "0.10"

